project:
  type: website

website:
  title: "Exploratory Philology Blog"
  navbar:
    background: seagreen
    right:
      - about.qmd
      - icon: github
        href: https://github.com/diyclassics
      - icon: twitter
        href: https://twitter.com/diyclassics
format:
  html:
    theme: cosmo
    css: styles.css