project:
  type: website
  render:
    - "!posts/pleias-tokenizer/"
    - "!posts/tool-rnntagger/"
    - "**/*.qmd"
    - "**/*.ipynb"

execute:
  freeze: auto

website:
  title: "Exploratory Philology Blog"
  draft-mode: gone
  navbar:
    background: seagreen
    right:
      - about.qmd
      - icon: github
        href: https://github.com/diyclassics
      - icon: twitter
        href: https://twitter.com/diyclassics

format:
  html:
    theme: cosmo
    css: styles.css
